
# See here https://devspace.cloud/docs/cli/deployment/components/configuration/overview-specification
# For information on how to configure this file,

# A list of containers that should run the pods of this component
containers: []
initContainers: []

service:
  # type: NodePort
  type: ClusterIP
  labels: {}
  annotations: {}
  ports: []
  externalIPs: []

labels: {}
annotations: {}

ingress:
  ingressClassName: nginx
  labels: {}
  annotations: {}
  rules: []

# Defines image pull secrets
# DevSpace CLI will append all pull secrets which are automatically created
# More infos on: https://devspace.cloud/docs/cli/image-building/workflow-basics#8-create-image-pull-secret
pullSecrets: []


env:

# ---- General Shared ENVs ---- #
  IMAGE_TAG: latest
  DOCKER_REGISTRY: ghcr.io
  IMAGE: 'ghcr.io/gobletqa/goblet-app'
  DISPLAY: ":0.0"
  # **IMPORTANT** - Must exactly match the version use in $GB_BASE_IMAGE_FROM
  PLAYWRIGHT_BROWSERS_VERSION: 1.27.0

  # Log file for all playwright logs
  # Gets set in container/scripts/resolveDSEnvs.js for screencast deployment
  PW_DEBUG_FILE: /goblet/app/logs/pwlogs.log

# ---- Goblet Action Shared ENVs ---- #
# These ENVs should be overwritten by the github action
  GOBLET_MOUNT_ROOT: /goblet/repos

  # Production url for gobletqa
  GB_GOBLET_URL: https://www.gobletqa.com

# ---- Goblet Shared ENVs ---- #
  GB_TOKEN: a-10K3n-g0bLe1
  GB_SH_LOCAL_MOUNT: goblet-local/current
  GB_SERVER_ORIGINS: 'http://localhost:19006,localhost,gobletqa.app,dev.gobletqa.app,gobletqa-develop.local.keghub.io,backend.dev.gobletqa.app'

  # TODO: @lance-tipton - Make this more dynamic - value comes from firebase?
  GB_GITHUB_AUTH_USERS: geoffrey.schultz@gmail.com,lancetipton04@gmail.com,lancetipton04+abstrakt@gmail.com
  GB_WS_TRANSPORTS: websocket

  # ---- Docker Images ---- #
  # Image tags added to all built images
  GB_IMAGE_BUILD_TAGS: values,package
  # Then, all sub goblet images are built from the goblet-base image
  GB_IMAGE_FROM: mcr.microsoft.com/playwright:v1.27.0-focal

  # ---- Logger ENVs ---- #
  # Enable to set custom log-level for conductor
  GB_LOG_LEVEL: debug
  GB_LOG_LABEL: Goblet
  GB_LOG_DISABLED: false
  GB_LOG_EXIT_ON_ERR: false
  GB_LOG_PRETTY_PRINT: true
  GB_LOG_HANDLE_EXCEPTION: true

# ---- App Development ENVs ---- #
  # Needed for conductor
  # Uncomment this to mount the whole repo into the container
  # GB_APP_DOC_VOLUMES: ".:/goblet/app,/var/run/docker.sock"
  GB_AUTH_ACTIVE: true
  GB_APP_MOUNT_PATH: /goblet/app

# ---- Backend ENVs ---- #
  GB_BE_PORT: 7005
  GB_BE_SECURE_PORT: 443
  # Host the FE uses to connect to the BE
  GB_BE_HOST: 0.0.0.0

  # Default to the backend api and host
  # But should be set when running as own server
  GB_BE_IMAGE_TAG: latest
  GB_BE_DEPLOYMENT: goblet-backend
  GB_BE_IMAGE: 'ghcr.io/gobletqa/goblet-backend'
  GB_BE_IMAGE_FROM: 'ubuntu:20.04'

  # ---- Backend Websocket ENVs ---- #
  GB_BE_WS_PATH: /goblet-socket
  GB_BE_WS_PROTOCOL: http

  # --- Backend JWT AUTH --- #
  GB_BE_JWT_EXP: '7200000'
  GB_BE_JWT_CREDENTIALS: true
  GB_BE_JWT_REFRESH_EXP: '7200000'
  GB_BE_JWT_SECRET: k3G-H3rkiN-1234
  GB_BE_JWT_KEY: goblet-be-auth-token
  GB_BE_JWT_REFRESH_SECRET: 4926-G0b13T-g3K

  # --- Backend COOKIE AUTH --- #
  # GB_BE_COOKIE_SECRET: ""
  GB_BE_COOKIE_SECURE: true
  GB_BE_COOKIE_NAME: goblet
  GB_BE_COOKIE_HTTP_ONLY: true
  GB_BE_COOKIE_OVERWRITE: true
  GB_BE_COOKIE_SAME_SITE: None
  GB_BE_COOKIE_KEY: goblet-cookie-7979

  # Disable certs in local. Set to the cluster issuer name in values.<env>.yaml file for ssl
  GB_BE_SECRET_TLS_NAME: false

# ---- Frontend ENVs ---- #
  GB_FE_PORT: 19006
  GB_FE_IMAGE_TAG: latest
  GB_FE_DEPLOYMENT: goblet-frontend
  GB_FE_IMAGE: 'ghcr.io/gobletqa/goblet-frontend'
  GB_FE_MOUNT_PATH: .:/goblet/app

# --- CONDUCTOR ENVs --- #
  # GB_CD_HOST: host.docker.internal
  GB_CD_HOST: local.gobletqa.app
  GB_CD_SUB_DOMAIN: conductor

  GB_CD_PIDS_LIMIT: 500
  GB_CD_RATE_LIMIT: 5000
  # TOOD: add this to set a timeout on a spawned container
  GB_CD_CONTAINER_TIMEOUT: 50000
  # Salting the user hash string. Not intended to be secure just anonymous
  GB_CD_HASH_KEY: C0nDuc10R
  GB_CD_CONTROLLER_TYPE: Kube

  # Timeout for the kube listener
  # Will kill and restart the listener on an interval
  # Works around issue where listener stops responding after some amount of time
  GB_CD_LISTENER_TIMEOUT: 250000

  # Conductor controller validation
  GB_CD_VALIDATION_KEY: "gb-cd-1234567"
  GB_CD_VALIDATION_HEADER: GB-CD-Validation-Key

  GB_CD_FORWARD_HOST_HEADER: x-goblet-host
  GB_CD_FORWARD_PORT_HEADER: x-goblet-port
  GB_CD_FORWARD_PROTO_HEADER: x-goblet-proto
  GB_CD_FORWARD_SUBDOMAIN_HEADER: x-goblet-subdomain

  # --- Certs ENVs --- #
  GB_CR_DEBUG: true
  GB_CR_CHART_TAG: 0.0.1
  GB_CR_MANAGE_ALL_NS: true
  GB_CR_DEPLOYMENT: goblet-certs
  GB_CR_CHART_URL: oci://ghcr.io/gobletqa/goblet-certs-chart

  GB_CR_SECRET_KEY: api-key
  GB_CR_SECRET: provider-auth
  GB_CR_USER_EMAIL: lancetipton04@gmail.com
  GB_CR_SECRET_ENV: ""
  GB_CR_SECRET_VALUE_PATH: ""

# --- SCREENCAST ENVs --- #
  GB_SC_IMAGE_TAG: latest
  GB_SC_DEPLOYMENT: goblet-screencast
  GB_SC_IMAGE: 'ghcr.io/gobletqa/goblet-screencast'
  # Screencast API port
  GB_SC_PORT: 7006
  # URL where the screencast is being displayed
  # This is the URL of the server the proxy connects to
  # Update this to call an externally available VNC websocket host
  GB_SC_HOST: 0.0.0.0

  GB_SC_WS_PATH: /goblet-socket

  # Port to forward connections from backend API to screencast
  GB_NO_VNC_PORT: 26369
  GB_NO_VNC_HOST: 0.0.0.0
  GB_NO_VNC_PATH: /novnc
  GB_NO_VNC_PROTOCOL: http

  # Host of VNC server for tigerVNC, that receives requests from the proxy
  # This is internal, and generally should not change
  GB_VNC_SERVER_HOST: 0.0.0.0
  GB_VNC_SERVER_PORT: 26370

  # Original
  # GB_VNC_VIEW_HEIGHT: 720
  # GB_VNC_VIEW_WIDTH: 1440

  # Width for wide-screen
  # GB_VNC_VIEW_HEIGHT: 1280
  # GB_VNC_VIEW_WIDTH: 1615

  # Width for mac-16in
  GB_VNC_VIEW_HEIGHT: 1430
  GB_VNC_VIEW_WIDTH: 1615


  GB_VNC_ACTIVE: true
  GB_PW_SOCKET_ACTIVE: false

  # --- CONTAINER TIMEOUT ENVs --- #
  GB_SC_TIMEOUT_ACTIVE: false
  # In minutes (x * 60000)
  GB_SC_INACTIVE_TIMEOUT: 20
  # In seconds (x * 1000)
  GB_SC_DISCONNECT_TIMEOUT: 20

  # Mount the app directory in the screencast repo
  # GB_SC_MOUNT_PATH: .:/goblet/app

# --- DIND ENVs --- #
  GB_DD_DOCKER_PORT: 2375
  GB_DD_DOCKER_HOST: 0.0.0.0
  # Required for dind
  GB_DD_PRIVILEGED: true
  GB_DD_IMAGE_TAG: latest
  GB_DD_NETWORK: goblet-proxy
  GB_DD_DEPLOYMENT: goblet-dind
  GB_DD_IMAGE: 'ghcr.io/gobletqa/goblet-dind'
  GB_DD_IMAGE_FROM: 'ubuntu:20.04'
  
  # Path where caddy will store files
  GB_DD_CADDY_REMOTE_DIR: /goblet/remote

  # Exposed Port used for all container API proxies
  GB_DD_API_PROXY_PORT: 2121

  # Exposed Port used for all container websocket proxies
  GB_DD_WS_PROXY_PORT: 2122

  # Exposed Port used for all container VNC proxies
  GB_DD_VNC_PROXY_PORT: 2123

  # Must be localhost due to caddy config, if can not be an ip address
  GB_DD_CADDY_HOST: goblet-dind
  GB_DD_EXP_ADMIN_PORT: 2018
  GB_DD_LOCAL_ADMIN_PORT: 2019

  GB_LOCAL_DEV_MODE: true

# --- KIND ENVs --- #
  GB_KD_DEPLOYMENT: goblet-kind
  GB_KD_ROLE_NAME: goblet-modify-pods
  GB_KD_SERVICE_ACCOUNT: goblet-pods-exec
  GB_KD_ROLE_BINDING_NAME: goblet-pods-role-binding

  # Exposed Port used for all container API proxies
  GB_KD_PORT: 2375
  GB_KD_HOST: 0.0.0.0
  GB_KD_SECURE_PORT: 443
  GB_KD_WS_PROXY_PORT: 2122
  GB_KD_VNC_PROXY_PORT: 2123
  GB_KD_WS_PATH: /goblet-socket


  GITLAB_OAUTH_ID: ""
  GITLAB_OAUTH_SECRET: ""