env:

# ---- General Shared ENVs ---- #

  GB_KUBE_CONTEXT: lke70246-ctx
  GB_KUBE_NAMESPACE: gb-production
  GB_HOST_DOMAIN: dev.gobletqa.app
  NODE_ENV: production
  GB_LOCAL_DEV_MODE: false
  DEVSPACE_INJECT_LOCAL: false

# ---- Backend ENVs ---- #
  # Use ssl in production, so port is always 443
  # The ingress will terminate and proxy to backend as 7005
  GB_BE_PORT: 443
  GB_BE_WS_PROTOCOL: https
  GB_BE_HOST: backend.dev.gobletqa.app
  # Name of the kubernetes secret used in the ingress
  GB_BE_SECRET_TLS_NAME: gb-production-tls

  # --- Goblet-Certs ENVs  --- #
  GB_CR_SECRET: provider-auth
  GB_CR_SECRET_KEY: token
  GB_CR_SECRET_ENV: LINODE_V4_API_KEY
  GB_CR_USER_EMAIL: lancetipton04@gmail.com
  GB_CR_SECRET_VALUE_PATH: "{{ cli.paths.config }}/linode/api-token"

  # --- VNC ENVs --- #
  # TODO: these will change if ever running locally and in production environment
  GB_VNC_ACTIVE: true
  GB_PW_SOCKET_ACTIVE: false
