env:

  GB_KUBE_CONTEXT: lke70246-ctx
  GB_KUBE_NAMESPACE: gb-production
  GB_HOST_DOMAIN: dev.gobletqa.app
  # GB_SUB_DOMAIN: production

  # Name of the kubernetes secret used in the ingress
  GB_BE_SECRET_TLS_NAME: gb-production-tls

  NODE_ENV: production
  GB_LOCAL_DEV_MODE: false
  DEVSPACE_INJECT_LOCAL: false

  # --- Cert-Manager - CLOUD PROVIDER ENVs --- #
  GB_CR_WEBHOOK_CHART_NAME: cert-manager-webhook-linode
  GB_CR_WEBHOOK_CHART_URL: https://github.com/slicen/cert-manager-webhook-linode/releases/download/v0.2.0/cert-manager-webhook-linode-v0.2.0.tgz
  GB_CR_SOLVER_NAME: linode
  GB_CR_NAMESPACE: cert-manager
  GB_CR_PROVIDER_TOKEN_KEY: token
  GB_CR_GROUP_NAME: dev.gobletqa.app
  GB_CR_USER_EMAIL: lancetipton04@gmail.com
  GB_CR_PROVIDER_TOKEN_NAME: linode-credentials
  GB_CR_PROVIDER_TOKEN_PATH: "{{ cli.paths.config }}/linode/api-token"
