env:

  GB_KUBE_CONTEXT: lke70246-ctx
  GB_KUBE_NAMESPACE: gb-production
  GB_HOST_DOMAIN: dev.gobletqa.app
  # GB_SUB_DOMAIN: production

  # Name of the kubernetes secret used in the ingress
  GB_BE_SECRET_TLS_NAME: gb-production-tls
  GB_BE_CERT_ISSUER: letsencrypt-production

  NODE_ENV: production
  GB_LOCAL_DEV_MODE: false
  DEVSPACE_INJECT_LOCAL: false
