export const stepsList = [
  `Given I navigate to {string}`,
  `When I wait for the url {string}`,
  `When I upload the file {string} to the element {string}`,
  `When I type {string} into the element {string}`,
  `When I set the text {string} to the element {string}`,
  `When I set the select {string} to {string} by {string}`,
  `When I set the media {string} state to {string}`,
  `When I press {string}`,
  `When I press the key {string}`,
  `When I move the mouse off the page`,
  `When I hover over the element {string}`,
  `When I focus on the element {string}`,
  `When I drag and drop the element {string} on to the element {string}`,
  `When I click the page`,
  `When I click text {string}`,
  `When I clear the element {string}`,
  `When I click the element {string}`,
  `When I move the mouse to {int}, {int}`,
  `When I grant the browser permission {string}`,
  `Then the element {string} checked state is {string}`,
  `Then the element {string} attribute {string} is {string}`,
  `Then the element {string} text is {string}`,
  `Then the page url is {string}`,
  `Then the page url contains {string}`,
  `Then the page title is one of {string}`,
  `Then the page title is not {string}`,
  `Then the page title is {string}`,
  `Then the page title contains {string}`,
  `Then the element {string} has class {string}`,
  `Then the select {string} selected option(s) is/are {string} by {string}`,
  `Then the element {string} style {string} is {string}`,
  `Then element {string} has child {string}`,
  `Then I ensure the checkbox {string} state is {string}`
]
