{{- if $.Values.serviceAccountMeta}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $.Values.serviceAccountMeta.name | quote }}
  labels:
    "app.kubernetes.io/name": "gobletqa-app"
    "app.kubernetes.io/component": {{ $.Release.Name | quote }}
    "app.kubernetes.io/managed-by": {{ $.Release.Service | quote }}
---
{{- end }}

{{- if $.Values.serviceAccountMeta.role}}
{{- $role := $.Values.serviceAccountMeta.role }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $role.name | quote }}
  labels:
    "app.kubernetes.io/name": "gobletqa-app"
    "app.kubernetes.io/component": {{ $.Release.Name | quote }}
    "app.kubernetes.io/managed-by": {{ $.Release.Service | quote }}
rules:
  - apiGroups: [""]
    resources:
    {{- range $resourceIndex, $resource := $role.resources }}
      - {{ $resource }}
    {{- end }}
    verbs:
    {{- range $verbIndex, $verb := $role.verbs }}
      - {{ $verb }}
    {{- end }}
---
{{- end }}

{{- if $.Values.serviceAccountMeta.binding }}
{{- $binding := $.Values.serviceAccountMeta.binding }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $binding.name  | quote }}
  labels:
    "app.kubernetes.io/name": "gobletqa-app"
    "app.kubernetes.io/component": {{ $.Release.Name | quote }}
    "app.kubernetes.io/managed-by": {{ $.Release.Service | quote }}
{{- if $binding.subjects }}
subjects:
  - kind: {{ $binding.subjects.kind | default "ServiceAccount" | quote }}
    name: {{ $binding.subjects.name | default $.Values.serviceAccountMeta.name | quote }}
{{- else }}
subjects:
  - kind: ServiceAccount
    name: {{ $.Values.serviceAccountMeta.name | quote }}
{{- end }}
{{- if $binding.ref }}
roleRef:
  kind: {{ $binding.ref.kind | default "Role" | quote }}
  name: {{ $binding.ref.name | default $.Values.serviceAccountMeta.role.name | quote }}
  apiGroup: {{ $binding.ref.group | default "rbac.authorization.k8s.io" | quote }}
{{- else }}
roleRef:
  kind: Role
  name: {{ $.Values.serviceAccountMeta.role.name | quote }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
---
{{- end }}