export { isStr } from '@keg-hub/jsutils/isStr'
export { isNum } from '@keg-hub/jsutils/isNum'
export { exists } from '@keg-hub/jsutils/exists'
export { identity } from '@keg-hub/jsutils/identity'
export { equalsNaN } from '@keg-hub/jsutils/equalsNaN'