
export enum ESectionType {
  feature='feature',
  Feature='feature',
  FEATURE='feature',
  rule='rule',
  Rule='rule',
  RULE='rule',
  background='background',
  Background='background',
  BACKGROUND='background',
  scenario='scenario',
  Scenario='scenario',
  SCENARIO='scenario',
  step='step',
  Step='step',
  STEP='step',
  steps='steps',
  Steps='steps',
  STEPS='steps',
  action='action',
  Action='action',
  ACTION='action',
}