# Creates a service account that will be used to make Kubernetes API calls
apiVersion: v1
kind: ServiceAccount
metadata:
  name: goblet-pods-exec

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: goblet-modify-pods
rules:
  - apiGroups: [""]
    resources: 
      - pods
      - pods/exec
    verbs:
      - create
      - delete
      - get
      - list
      - watch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: goblet-pods-role-binding
subjects:
  - kind: ServiceAccount
    name: goblet-pods-exec
roleRef:
  kind: Role
  name: goblet-modify-pods
  apiGroup: rbac.authorization.k8s.io
