export const FileTypeMap = {
  env: `env`,
  yml: `yaml`,
  html: `html`,
  json: `json`,
  yaml: `yaml`,
  js: `javascript`,
  jsx: `javascript`,
  cjs: `javascript`,
  mjs: `javascript`,
  ts: `typescript`,
  mts: `typescript`,
  cts: `typescript`,
  feature: `feature`,
}