export * from './AlertIcon'
export * from './Arrow'
export * from './BackspaceTagIcon'
export * from './DeleteIcon'
export * from './ExpandIcon'
export * from './FileIcon'
export * from './FileEditIcon'
export * from './FolderIcon'
export * from './FolderOpenIcon'
export * from './Git'
export * from './GobletIcon'
export * from './MaterialIcons'
export * from './NewFileIcon'
export * from './NewFolderIcon'
export * from './PencilIcon'
export * from './RecordIcon'
export * from './StateIcon'
export * from './TrashIcon'
export * from './GitTreeSvg'
export * from './PencilAdd'
export * from './PlusIcon'
export * from './TextboxPlus'
export * from './StepAddIcon'
export * from './FootIcon'

export * from './ShapesPlusIcon'
export * from './TrayPlusIcon'
export * from './ListPlusIcon'
export * from './PlaylistPlusIcon'
export * from './TabPlusIcon'
export * from './CardPlusIcon'
export * from './NotePlusIcon'
export * from './NoteMinusIcon'
export * from './ReflectHorIcon'
export * from './UserDetailsIcon'
export * from './CircleMinusIcon'
export * from './CursorClickIcon'

// -- TODO - Use for dragging on top of the browser
// export * from './SelectDragIcon'

// export * from './PlayCircleIcon'
// export * from './PlayOutlineIcon'
// export * from './PlayIcon'
// export * from './BorderNoneIcon'
// export * from './ThreeDotIcon'
// export * from './BrowserIcon'
// export * from './AutoFixIcon'
// export * from './SquareIcon'
// export * from './CirclesIcon'
// export * from './PlayPauseIcon'
// export * from './TimerSandIcon'
// export * from './TimerSandEmptyIcon'
// export * from './UserPlus'
// export * from './EyeOffIcon'
// export * from './ShoePrintIcon'
// export * from './UserAccountIcon'
// export * from './FileOutlinePlus'