export const ExamEvtNames = {
  specDone: `PLAY-SPEC-DONE`,
  specWarn: `PLAY-SPEC-WARN`,
  specStart: `PLAY-SPEC-START`,
  suiteDone: `PLAY-SUITE-DONE`,
  suiteStart: `PLAY-SUITE-START`,
  rootSuiteDone: `PLAY-SUITE-DONE-ROOT`,
  rootSuiteStart: `PLAY-SUITE-START-ROOT`,
  ended: `PLAY-ENDED`,
  error: `PLAY-ERROR`,
  action: `PLAY-ACTION`,
  general: `PLAY-GENERAL`,
  results: `PLAY-RESULTS`,
  started: `PLAY-STARTED`,
  canceled: `PLAY-CANCELED`,
  stopped: `PLAY-STOPPED`,
  warning: `PLAY-WARNING`,
}
