import type { TTestRuns } from '@types'

export const testRunMockName = `end-2-end.1695274695460`
export const testRunMockName2 = `end-2-end.1695275353386`
export const testRunMocks:TTestRuns = {
  [testRunMockName]: [
    {
        "id": "e2d722ef-736b-41ad-a1d3-7613f165a1f0",
        "message": "Exam started",
        "error": false,
        "data": {
            "id": "File-Upload",
            "stats": {
                "runEnd": 0,
                "failedSpecs": 0,
                "passedSpecs": 0,
                "passedSuites": 0,
                "failedSuites": 0,
                "runStart": 1695274700285
            },
            "action": "start",
            "testPath": "/goblet/repos/lancetipton/goblet/bdd/features/Steps/File-Upload.feature",
            "fullName": "/goblet/repos/lancetipton/goblet/bdd/features/Steps/File-Upload.feature",
            "type": "feature",
            "failed": false,
            "passed": false,
            "description": "Feature - running",
            "timestamp": 1695274700285,
            "location": "/goblet/repos/lancetipton/goblet/bdd/features/Steps/File-Upload.feature",
            "eventParent": "feature"
        },
        "group": "qtutdh8m8L6Sqor-AAAH",
        "name": "PLAY-STARTED",
        "isRunning": false,
        "timestamp": 1695274700286,
        "fullTestRun": true,
        "procId": 19921,
        "runId": "end-2-end.1695274695460",
        "runTimestamp": 1695274695460,
        "location": "/goblet/repos/lancetipton/goblet/bdd/features/Steps/File-Upload.feature",
        "socketId": "qtutdh8m8L6Sqor-AAAH",
        "groupId": "goblet"
    },
    {
        "id": "4ea7a6ea-ee81-445e-9f01-801a5d46a1ce",
        "message": "Exam - Suite Results",
        "error": false,
        "data": {
            "id": "root",
            "stats": {
                "runEnd": 1695274702100,
                "failedSpecs": 0,
                "passedSpecs": 4,
                "passedSuites": 2,
                "failedSuites": 0,
                "runStart": 1695274700285
            },
            "action": "end",
            "testPath": "/root",
            "type": "root",
            "passedExpectations": [],
            "failed": false,
            "passed": true,
            "description": "Feature - passed",
            "timestamp": 1695274700285,
            "describes": [],
            "status": "passed",
            "location": "/goblet/repos/lancetipton/goblet/bdd/features/Steps/File-Upload.feature",
            "eventParent": "feature"
        },
        "group": "qtutdh8m8L6Sqor-AAAH",
        "name": "PLAY-RESULTS",
        "isRunning": false,
        "timestamp": 1695274702101,
        "fullTestRun": true,
        "procId": 19921,
        "runId": "end-2-end.1695274695460",
        "runTimestamp": 1695274695460,
        "location": "/goblet/repos/lancetipton/goblet/bdd/features/Steps/File-Upload.feature",
        "socketId": "qtutdh8m8L6Sqor-AAAH",
        "groupId": "goblet"
    },
    {
        "id": "108f4917-d545-4e2b-9ede-bfba53230815",
        "message": "Exam - Suite Started",
        "error": false,
        "data": {
            "id": "suite-0-0",
            "stats": {
                "runEnd": 0,
                "failedSpecs": 0,
                "passedSpecs": 0,
                "passedSuites": 0,
                "failedSuites": 0,
                "runStart": 1695274700285
            },
            "action": "start",
            "testPath": "/suite-0-0",
            "fullName": "Scenario > Steps",
            "type": "describe",
            "failed": false,
            "passed": false,
            "description": "Scenario - running",
            "timestamp": 1695274700750,
            "metaData": {
                "disabled": false,
                "index": 3,
                "uuid": "feature-1979245909.scenario.0",
                "tags": {
                    "index": 2,
                    "tokens": [
                        "@goblet-simple-steps"
                    ],
                    "content": "@goblet-simple-steps",
                    "type": "tags",
                    "uuid": "tags-2117646448",
                    "whitespace": "  "
                },
                "type": "scenario",
                "scenario": "Steps"
            },
            "location": "/goblet/repos/lancetipton/goblet/bdd/features/Steps/File-Upload.feature",
            "eventParent": "scenario"
        },
        "group": "qtutdh8m8L6Sqor-AAAH",
        "name": "PLAY-SUITE-START",
        "isRunning": false,
        "timestamp": 1695274700751,
        "fullTestRun": true,
        "procId": 19921,
        "runId": "end-2-end.1695274695460",
        "runTimestamp": 1695274695460,
        "location": "/goblet/repos/lancetipton/goblet/bdd/features/Steps/File-Upload.feature",
        "socketId": "qtutdh8m8L6Sqor-AAAH",
        "groupId": "goblet"
    },
    {
        "id": "7e4a3410-5ef7-4837-9e96-091458f77a8a",
        "message": "Exam - Spec Started",
        "error": false,
        "data": {
            "id": "spec-0",
            "stats": {
                "runEnd": 0,
                "failedSpecs": 0,
                "passedSpecs": 0,
                "passedSuites": 0,
                "failedSuites": 0,
                "runStart": 1695274700285
            },
            "action": "start",
            "testPath": "/suite-0-0/spec-0",
            "fullName": "Scenario > Steps > Given I navigate to 'https://testpages.eviltester.com/styled/file-upload-test.html'",
            "type": "test",
            "failed": false,
            "passed": false,
            "description": "Step - running",
            "timestamp": 1695274700750,
            "metaData": {
                "disabled": false,
                "uuid": "feature-1979245909.scenario.0.given.0",
                "step": "I navigate to 'https://testpages.eviltester.com/styled/file-upload-test.html'",
                "index": 4,
                "type": "given"
            },
            "location": "/goblet/repos/lancetipton/goblet/bdd/features/Steps/File-Upload.feature",
            "eventParent": "step"
        },
        "group": "qtutdh8m8L6Sqor-AAAH",
        "name": "PLAY-SPEC-START",
        "isRunning": false,
        "timestamp": 1695274700751,
        "fullTestRun": true,
        "procId": 19921,
        "runId": "end-2-end.1695274695460",
        "runTimestamp": 1695274695460,
        "location": "/goblet/repos/lancetipton/goblet/bdd/features/Steps/File-Upload.feature",
        "socketId": "qtutdh8m8L6Sqor-AAAH",
        "groupId": "goblet"
    },
    {
        "id": "7ad8e3ff-4b9a-4d76-996a-17f1b029c6a6",
        "message": "Exam - Suite Done",
        "error": false,
        "data": {
            "id": "suite-0-0",
            "stats": {
                "runEnd": 0,
                "failedSpecs": 0,
                "passedSpecs": 4,
                "passedSuites": 1,
                "failedSuites": 0,
                "runStart": 1695274700285
            },
            "action": "end",
            "testPath": "/suite-0-0",
            "fullName": "Scenario > Steps",
            "type": "describe",
            "failed": false,
            "passed": true,
            "description": "Scenario - passed",
            "timestamp": 1695274700750,
            "metaData": {
                "disabled": false,
                "index": 3,
                "uuid": "feature-1979245909.scenario.0",
                "tags": {
                    "index": 2,
                    "tokens": [
                        "@goblet-simple-steps"
                    ],
                    "content": "@goblet-simple-steps",
                    "type": "tags",
                    "uuid": "tags-2117646448",
                    "whitespace": "  "
                },
                "type": "scenario",
                "scenario": "Steps"
            },
            "status": "passed",
            "location": "/goblet/repos/lancetipton/goblet/bdd/features/Steps/File-Upload.feature",
            "eventParent": "scenario"
        },
        "group": "qtutdh8m8L6Sqor-AAAH",
        "name": "PLAY-SUITE-DONE",
        "isRunning": false,
        "timestamp": 1695274702085,
        "fullTestRun": true,
        "procId": 19921,
        "runId": "end-2-end.1695274695460",
        "runTimestamp": 1695274695460,
        "location": "/goblet/repos/lancetipton/goblet/bdd/features/Steps/File-Upload.feature",
        "socketId": "qtutdh8m8L6Sqor-AAAH",
        "groupId": "goblet"
    },
    {
        "id": "89d986ae-bfa7-46f0-94ad-6d16c33d898b",
        "message": "Exam - Spec Done",
        "error": false,
        "data": {
            "id": "spec-0",
            "stats": {
                "runEnd": 0,
                "failedSpecs": 0,
                "passedSpecs": 1,
                "passedSuites": 0,
                "failedSuites": 0,
                "runStart": 1695274700285
            },
            "action": "end",
            "testPath": "/suite-0-0/spec-0",
            "fullName": "Scenario > Steps > Given I navigate to 'https://testpages.eviltester.com/styled/file-upload-test.html'",
            "type": "test",
            "failed": false,
            "passed": true,
            "description": "Step - passed",
            "timestamp": 1695274701509,
            "metaData": {
                "disabled": false,
                "uuid": "feature-1979245909.scenario.0.given.0",
                "step": "I navigate to 'https://testpages.eviltester.com/styled/file-upload-test.html'",
                "index": 4,
                "type": "given"
            },
            "status": "passed",
            "location": "/goblet/repos/lancetipton/goblet/bdd/features/Steps/File-Upload.feature",
            "eventParent": "step"
        },
        "group": "qtutdh8m8L6Sqor-AAAH",
        "name": "PLAY-SPEC-DONE",
        "isRunning": false,
        "timestamp": 1695274701510,
        "fullTestRun": true,
        "procId": 19921,
        "runId": "end-2-end.1695274695460",
        "runTimestamp": 1695274695460,
        "location": "/goblet/repos/lancetipton/goblet/bdd/features/Steps/File-Upload.feature",
        "socketId": "qtutdh8m8L6Sqor-AAAH",
        "groupId": "goblet"
    },
    {
        "id": "0b63a208-6670-42b5-b0e2-e07d08e23e58",
        "message": "Exam - Spec Started",
        "error": false,
        "data": {
            "id": "spec-1",
            "stats": {
                "runEnd": 0,
                "failedSpecs": 0,
                "passedSpecs": 1,
                "passedSuites": 0,
                "failedSuites": 0,
                "runStart": 1695274700285
            },
            "action": "start",
            "testPath": "/suite-0-0/spec-1",
            "fullName": "Scenario > Steps > When I upload the file 'test-upload.txt' to the element '#fileinput'",
            "type": "test",
            "failed": false,
            "passed": false,
            "description": "Step - running",
            "timestamp": 1695274701510,
            "metaData": {
                "disabled": false,
                "uuid": "feature-1979245909.scenario.0.when.1",
                "step": "I upload the file 'test-upload.txt' to the element '#fileinput'",
                "index": 5,
                "type": "when"
            },
            "location": "/goblet/repos/lancetipton/goblet/bdd/features/Steps/File-Upload.feature",
            "eventParent": "step"
        },
        "group": "qtutdh8m8L6Sqor-AAAH",
        "name": "PLAY-SPEC-START",
        "isRunning": false,
        "timestamp": 1695274701511,
        "fullTestRun": true,
        "procId": 19921,
        "runId": "end-2-end.1695274695460",
        "runTimestamp": 1695274695460,
        "location": "/goblet/repos/lancetipton/goblet/bdd/features/Steps/File-Upload.feature",
        "socketId": "qtutdh8m8L6Sqor-AAAH",
        "groupId": "goblet"
    },
    {
        "id": "13260694-a455-43f6-9935-9b9a1d10bcca",
        "message": "Exam - Spec Done",
        "error": false,
        "data": {
            "id": "spec-1",
            "stats": {
                "runEnd": 0,
                "failedSpecs": 0,
                "passedSpecs": 2,
                "passedSuites": 0,
                "failedSuites": 0,
                "runStart": 1695274700285
            },
            "action": "end",
            "testPath": "/suite-0-0/spec-1",
            "fullName": "Scenario > Steps > When I upload the file 'test-upload.txt' to the element '#fileinput'",
            "type": "test",
            "failed": false,
            "passed": true,
            "description": "Step - passed",
            "timestamp": 1695274701652,
            "metaData": {
                "disabled": false,
                "uuid": "feature-1979245909.scenario.0.when.1",
                "step": "I upload the file 'test-upload.txt' to the element '#fileinput'",
                "index": 5,
                "type": "when"
            },
            "status": "passed",
            "location": "/goblet/repos/lancetipton/goblet/bdd/features/Steps/File-Upload.feature",
            "eventParent": "step"
        },
        "group": "qtutdh8m8L6Sqor-AAAH",
        "name": "PLAY-SPEC-DONE",
        "isRunning": false,
        "timestamp": 1695274701652,
        "fullTestRun": true,
        "procId": 19921,
        "runId": "end-2-end.1695274695460",
        "runTimestamp": 1695274695460,
        "location": "/goblet/repos/lancetipton/goblet/bdd/features/Steps/File-Upload.feature",
        "socketId": "qtutdh8m8L6Sqor-AAAH",
        "groupId": "goblet"
    },
    {
        "id": "794c73f7-f7d4-48f5-be82-ae1e1ddd2921",
        "message": "Exam - Spec Started",
        "error": false,
        "data": {
            "id": "spec-2",
            "stats": {
                "runEnd": 0,
                "failedSpecs": 0,
                "passedSpecs": 2,
                "passedSuites": 0,
                "failedSuites": 0,
                "runStart": 1695274700285
            },
            "action": "start",
            "testPath": "/suite-0-0/spec-2",
            "fullName": "Scenario > Steps > When I click 'internal:text=\"A General File\"i'",
            "type": "test",
            "failed": false,
            "passed": false,
            "description": "Step - running",
            "timestamp": 1695274701652,
            "metaData": {
                "disabled": false,
                "uuid": "feature-1979245909.scenario.0.when.2",
                "step": "I click 'internal:text=\"A General File\"i'",
                "index": 6,
                "type": "when"
            },
            "location": "/goblet/repos/lancetipton/goblet/bdd/features/Steps/File-Upload.feature",
            "eventParent": "step"
        },
        "group": "qtutdh8m8L6Sqor-AAAH",
        "name": "PLAY-SPEC-START",
        "isRunning": false,
        "timestamp": 1695274701653,
        "fullTestRun": true,
        "procId": 19921,
        "runId": "end-2-end.1695274695460",
        "runTimestamp": 1695274695460,
        "location": "/goblet/repos/lancetipton/goblet/bdd/features/Steps/File-Upload.feature",
        "socketId": "qtutdh8m8L6Sqor-AAAH",
        "groupId": "goblet"
    },
    {
        "id": "20919fc3-46a7-4e94-ab52-c59c001d61ad",
        "message": "Exam - Spec Done",
        "error": false,
        "data": {
            "id": "spec-2",
            "stats": {
                "runEnd": 0,
                "failedSpecs": 0,
                "passedSpecs": 3,
                "passedSuites": 0,
                "failedSuites": 0,
                "runStart": 1695274700285
            },
            "action": "end",
            "testPath": "/suite-0-0/spec-2",
            "fullName": "Scenario > Steps > When I click 'internal:text=\"A General File\"i'",
            "type": "test",
            "failed": false,
            "passed": true,
            "description": "Step - passed",
            "timestamp": 1695274701779,
            "metaData": {
                "disabled": false,
                "uuid": "feature-1979245909.scenario.0.when.2",
                "step": "I click 'internal:text=\"A General File\"i'",
                "index": 6,
                "type": "when"
            },
            "status": "passed",
            "location": "/goblet/repos/lancetipton/goblet/bdd/features/Steps/File-Upload.feature",
            "eventParent": "step"
        },
        "group": "qtutdh8m8L6Sqor-AAAH",
        "name": "PLAY-SPEC-DONE",
        "isRunning": false,
        "timestamp": 1695274701780,
        "fullTestRun": true,
        "procId": 19921,
        "runId": "end-2-end.1695274695460",
        "runTimestamp": 1695274695460,
        "location": "/goblet/repos/lancetipton/goblet/bdd/features/Steps/File-Upload.feature",
        "socketId": "qtutdh8m8L6Sqor-AAAH",
        "groupId": "goblet"
    },
    {
        "id": "1a2d3ac3-e1d2-4a3f-b019-9c3c4324ccb6",
        "message": "Exam - Spec Started",
        "error": false,
        "data": {
            "id": "spec-3",
            "stats": {
                "runEnd": 0,
                "failedSpecs": 0,
                "passedSpecs": 3,
                "passedSuites": 0,
                "failedSuites": 0,
                "runStart": 1695274700285
            },
            "action": "start",
            "testPath": "/suite-0-0/spec-3",
            "fullName": "Scenario > Steps > When I click 'internal:role=button[name=\"Upload\"i]'",
            "type": "test",
            "failed": false,
            "passed": false,
            "description": "Step - running",
            "timestamp": 1695274701779,
            "metaData": {
                "disabled": false,
                "uuid": "feature-1979245909.scenario.0.when.3",
                "step": "I click 'internal:role=button[name=\"Upload\"i]'",
                "index": 7,
                "type": "when"
            },
            "location": "/goblet/repos/lancetipton/goblet/bdd/features/Steps/File-Upload.feature",
            "eventParent": "step"
        },
        "group": "qtutdh8m8L6Sqor-AAAH",
        "name": "PLAY-SPEC-START",
        "isRunning": false,
        "timestamp": 1695274701780,
        "fullTestRun": true,
        "procId": 19921,
        "runId": "end-2-end.1695274695460",
        "runTimestamp": 1695274695460,
        "location": "/goblet/repos/lancetipton/goblet/bdd/features/Steps/File-Upload.feature",
        "socketId": "qtutdh8m8L6Sqor-AAAH",
        "groupId": "goblet"
    },
    {
        "id": "e27c7273-8894-46e3-9a3f-f653419a0694",
        "message": "Exam - Spec Done",
        "error": false,
        "data": {
            "id": "spec-3",
            "stats": {
                "runEnd": 0,
                "failedSpecs": 0,
                "passedSpecs": 4,
                "passedSuites": 0,
                "failedSuites": 0,
                "runStart": 1695274700285
            },
            "action": "end",
            "testPath": "/suite-0-0/spec-3",
            "fullName": "Scenario > Steps > When I click 'internal:role=button[name=\"Upload\"i]'",
            "type": "test",
            "failed": false,
            "passed": true,
            "description": "Step - passed",
            "timestamp": 1695274702084,
            "metaData": {
                "disabled": false,
                "uuid": "feature-1979245909.scenario.0.when.3",
                "step": "I click 'internal:role=button[name=\"Upload\"i]'",
                "index": 7,
                "type": "when"
            },
            "status": "passed",
            "location": "/goblet/repos/lancetipton/goblet/bdd/features/Steps/File-Upload.feature",
            "eventParent": "step"
        },
        "group": "qtutdh8m8L6Sqor-AAAH",
        "name": "PLAY-SPEC-DONE",
        "isRunning": false,
        "timestamp": 1695274702085,
        "fullTestRun": true,
        "procId": 19921,
        "runId": "end-2-end.1695274695460",
        "runTimestamp": 1695274695460,
        "location": "/goblet/repos/lancetipton/goblet/bdd/features/Steps/File-Upload.feature",
        "socketId": "qtutdh8m8L6Sqor-AAAH",
        "groupId": "goblet"
    }
  ],
  [testRunMockName2]: [
    {
        "id": "ab7c1422-a4aa-4ecc-b213-3e3b4dea507d",
        "message": "Exam started",
        "error": false,
        "data": {
            "id": "Secrets-Url",
            "stats": {
                "runEnd": 0,
                "failedSpecs": 0,
                "passedSpecs": 0,
                "passedSuites": 0,
                "failedSuites": 0,
                "runStart": 1695275355735
            },
            "action": "start",
            "testPath": "/goblet/repos/lancetipton/goblet/bdd/features/Secrets/Secrets-Url.feature",
            "fullName": "/goblet/repos/lancetipton/goblet/bdd/features/Secrets/Secrets-Url.feature",
            "type": "feature",
            "failed": false,
            "passed": false,
            "description": "Feature - running",
            "timestamp": 1695275355735,
            "location": "/goblet/repos/lancetipton/goblet/bdd/features/Secrets/Secrets-Url.feature",
            "eventParent": "feature"
        },
        "group": "N4SKwa5wwdTgrkQiAAAN",
        "name": "PLAY-STARTED",
        "isRunning": false,
        "timestamp": 1695275355737,
        "fullTestRun": true,
        "procId": 20369,
        "runId": "end-2-end.1695275353386",
        "runTimestamp": 1695275353386,
        "location": "/goblet/repos/lancetipton/goblet/bdd/features/Secrets/Secrets-Url.feature",
        "socketId": "N4SKwa5wwdTgrkQiAAAN",
        "groupId": "goblet"
    },
    {
        "id": "00dc89a2-d506-42dd-8a65-97960318b1bd",
        "message": "Exam - Suite Results",
        "error": false,
        "data": {
            "id": "root",
            "stats": {
                "runEnd": 1695275357833,
                "failedSpecs": 0,
                "passedSpecs": 6,
                "passedSuites": 2,
                "failedSuites": 0,
                "runStart": 1695275355735
            },
            "action": "end",
            "testPath": "/root",
            "fullName": "root",
            "type": "root",
            "passedExpectations": [],
            "failed": false,
            "passed": true,
            "description": "Feature - passed",
            "timestamp": 1695275355735,
            "describes": [],
            "status": "passed",
            "location": "/goblet/repos/lancetipton/goblet/bdd/features/Secrets/Secrets-Url.feature",
            "eventParent": "feature"
        },
        "group": "N4SKwa5wwdTgrkQiAAAN",
        "name": "PLAY-RESULTS",
        "isRunning": false,
        "timestamp": 1695275357836,
        "fullTestRun": true,
        "procId": 20369,
        "runId": "end-2-end.1695275353386",
        "runTimestamp": 1695275353386,
        "location": "/goblet/repos/lancetipton/goblet/bdd/features/Secrets/Secrets-Url.feature",
        "socketId": "N4SKwa5wwdTgrkQiAAAN",
        "groupId": "goblet"
    },
    {
        "id": "42474414-643c-4697-a412-681245c327bf",
        "message": "Exam - Suite Started",
        "error": false,
        "data": {
            "id": "suite-0-0",
            "stats": {
                "runEnd": 0,
                "failedSpecs": 0,
                "passedSpecs": 0,
                "passedSuites": 0,
                "failedSuites": 0,
                "runStart": 1695275355735
            },
            "action": "start",
            "testPath": "/suite-0-0",
            "fullName": "Scenario > Steps",
            "type": "describe",
            "failed": false,
            "passed": false,
            "description": "Scenario - running",
            "timestamp": 1695275357015,
            "metaData": {
                "disabled": false,
                "index": 4,
                "uuid": "feature-82173692.scenario.0",
                "tags": {
                    "index": 3,
                    "tokens": [
                        "@goblet-simple-steps"
                    ],
                    "content": "@goblet-simple-steps",
                    "type": "tags",
                    "uuid": "tags-2117646448",
                    "whitespace": "  "
                },
                "type": "scenario",
                "scenario": "Steps"
            },
            "location": "/goblet/repos/lancetipton/goblet/bdd/features/Secrets/Secrets-Url.feature",
            "eventParent": "scenario"
        },
        "group": "N4SKwa5wwdTgrkQiAAAN",
        "name": "PLAY-SUITE-START",
        "isRunning": false,
        "timestamp": 1695275357026,
        "fullTestRun": true,
        "procId": 20369,
        "runId": "end-2-end.1695275353386",
        "runTimestamp": 1695275353386,
        "location": "/goblet/repos/lancetipton/goblet/bdd/features/Secrets/Secrets-Url.feature",
        "socketId": "N4SKwa5wwdTgrkQiAAAN",
        "groupId": "goblet"
    },
    {
        "id": "2ed9ca3d-600a-4e81-b49c-3400847ebf08",
        "message": "Exam - Suite Done",
        "error": false,
        "data": {
            "id": "suite-0-0",
            "stats": {
                "runEnd": 0,
                "failedSpecs": 0,
                "passedSpecs": 6,
                "passedSuites": 1,
                "failedSuites": 0,
                "runStart": 1695275355735
            },
            "action": "end",
            "testPath": "/suite-0-0",
            "fullName": "Scenario > Steps",
            "type": "describe",
            "failed": false,
            "passed": true,
            "description": "Scenario - passed",
            "timestamp": 1695275357015,
            "metaData": {
                "disabled": false,
                "index": 4,
                "uuid": "feature-82173692.scenario.0",
                "tags": {
                    "index": 3,
                    "tokens": [
                        "@goblet-simple-steps"
                    ],
                    "content": "@goblet-simple-steps",
                    "type": "tags",
                    "uuid": "tags-2117646448",
                    "whitespace": "  "
                },
                "type": "scenario",
                "scenario": "Steps"
            },
            "status": "passed",
            "location": "/goblet/repos/lancetipton/goblet/bdd/features/Secrets/Secrets-Url.feature",
            "eventParent": "scenario"
        },
        "group": "N4SKwa5wwdTgrkQiAAAN",
        "name": "PLAY-SUITE-DONE",
        "isRunning": false,
        "timestamp": 1695275357807,
        "fullTestRun": true,
        "procId": 20369,
        "runId": "end-2-end.1695275353386",
        "runTimestamp": 1695275353386,
        "location": "/goblet/repos/lancetipton/goblet/bdd/features/Secrets/Secrets-Url.feature",
        "socketId": "N4SKwa5wwdTgrkQiAAAN",
        "groupId": "goblet"
    },
    {
        "id": "d8d4a9fc-da34-4511-8dbc-53aad99e58e6",
        "message": "Exam - Spec Started",
        "error": false,
        "data": {
            "id": "spec-0",
            "stats": {
                "runEnd": 0,
                "failedSpecs": 0,
                "passedSpecs": 0,
                "passedSuites": 0,
                "failedSuites": 0,
                "runStart": 1695275355735
            },
            "action": "start",
            "testPath": "/suite-0-0/spec-0",
            "fullName": "Scenario > Steps > Given I navigate to '$world.secrets.GOBLET_QA_DOCS_URL'",
            "type": "test",
            "failed": false,
            "passed": false,
            "description": "Step - running",
            "timestamp": 1695275357016,
            "metaData": {
                "disabled": false,
                "uuid": "feature-82173692.scenario.0.given.0",
                "step": "I navigate to '$world.secrets.GOBLET_QA_DOCS_URL'",
                "index": 5,
                "type": "given"
            },
            "location": "/goblet/repos/lancetipton/goblet/bdd/features/Secrets/Secrets-Url.feature",
            "eventParent": "step"
        },
        "group": "N4SKwa5wwdTgrkQiAAAN",
        "name": "PLAY-SPEC-START",
        "isRunning": false,
        "timestamp": 1695275357078,
        "fullTestRun": true,
        "procId": 20369,
        "runId": "end-2-end.1695275353386",
        "runTimestamp": 1695275353386,
        "location": "/goblet/repos/lancetipton/goblet/bdd/features/Secrets/Secrets-Url.feature",
        "socketId": "N4SKwa5wwdTgrkQiAAAN",
        "groupId": "goblet"
    },
    {
        "id": "c990c47d-63f0-4ca7-82e7-f5a0e965c7a4",
        "message": "Exam - Spec Done",
        "error": false,
        "data": {
            "id": "spec-0",
            "stats": {
                "runEnd": 0,
                "failedSpecs": 0,
                "passedSpecs": 1,
                "passedSuites": 0,
                "failedSuites": 0,
                "runStart": 1695275355735
            },
            "action": "end",
            "testPath": "/suite-0-0/spec-0",
            "fullName": "Scenario > Steps > Given I navigate to '$world.secrets.GOBLET_QA_DOCS_URL'",
            "type": "test",
            "failed": false,
            "passed": true,
            "description": "Step - passed",
            "timestamp": 1695275357536,
            "metaData": {
                "disabled": false,
                "uuid": "feature-82173692.scenario.0.given.0",
                "step": "I navigate to '$world.secrets.GOBLET_QA_DOCS_URL'",
                "index": 5,
                "type": "given"
            },
            "status": "passed",
            "location": "/goblet/repos/lancetipton/goblet/bdd/features/Secrets/Secrets-Url.feature",
            "eventParent": "step"
        },
        "group": "N4SKwa5wwdTgrkQiAAAN",
        "name": "PLAY-SPEC-DONE",
        "isRunning": false,
        "timestamp": 1695275357545,
        "fullTestRun": true,
        "procId": 20369,
        "runId": "end-2-end.1695275353386",
        "runTimestamp": 1695275353386,
        "location": "/goblet/repos/lancetipton/goblet/bdd/features/Secrets/Secrets-Url.feature",
        "socketId": "N4SKwa5wwdTgrkQiAAAN",
        "groupId": "goblet"
    },
    {
        "id": "c7ea3471-5d14-4c61-acd3-7fb7a538a919",
        "message": "Exam - Spec Started",
        "error": false,
        "data": {
            "id": "spec-1",
            "stats": {
                "runEnd": 0,
                "failedSpecs": 0,
                "passedSpecs": 1,
                "passedSuites": 0,
                "failedSuites": 0,
                "runStart": 1695275355735
            },
            "action": "start",
            "testPath": "/suite-0-0/spec-1",
            "fullName": "Scenario > Steps > When I wait for the page to load",
            "type": "test",
            "failed": false,
            "passed": false,
            "description": "Step - running",
            "timestamp": 1695275357537,
            "metaData": {
                "disabled": false,
                "uuid": "feature-82173692.scenario.0.when.1",
                "step": "I wait for the page to load",
                "index": 6,
                "type": "when"
            },
            "location": "/goblet/repos/lancetipton/goblet/bdd/features/Secrets/Secrets-Url.feature",
            "eventParent": "step"
        },
        "group": "N4SKwa5wwdTgrkQiAAAN",
        "name": "PLAY-SPEC-START",
        "isRunning": false,
        "timestamp": 1695275357548,
        "fullTestRun": true,
        "procId": 20369,
        "runId": "end-2-end.1695275353386",
        "runTimestamp": 1695275353386,
        "location": "/goblet/repos/lancetipton/goblet/bdd/features/Secrets/Secrets-Url.feature",
        "socketId": "N4SKwa5wwdTgrkQiAAAN",
        "groupId": "goblet"
    },
    {
        "id": "64d54986-84f5-4a6c-b3c7-7c1714293651",
        "message": "Exam - Spec Done",
        "error": false,
        "data": {
            "id": "spec-1",
            "stats": {
                "runEnd": 0,
                "failedSpecs": 0,
                "passedSpecs": 2,
                "passedSuites": 0,
                "failedSuites": 0,
                "runStart": 1695275355735
            },
            "action": "end",
            "testPath": "/suite-0-0/spec-1",
            "fullName": "Scenario > Steps > When I wait for the page to load",
            "type": "test",
            "failed": false,
            "passed": true,
            "description": "Step - passed",
            "timestamp": 1695275357559,
            "metaData": {
                "disabled": false,
                "uuid": "feature-82173692.scenario.0.when.1",
                "step": "I wait for the page to load",
                "index": 6,
                "type": "when"
            },
            "status": "passed",
            "location": "/goblet/repos/lancetipton/goblet/bdd/features/Secrets/Secrets-Url.feature",
            "eventParent": "step"
        },
        "group": "N4SKwa5wwdTgrkQiAAAN",
        "name": "PLAY-SPEC-DONE",
        "isRunning": false,
        "timestamp": 1695275357560,
        "fullTestRun": true,
        "procId": 20369,
        "runId": "end-2-end.1695275353386",
        "runTimestamp": 1695275353386,
        "location": "/goblet/repos/lancetipton/goblet/bdd/features/Secrets/Secrets-Url.feature",
        "socketId": "N4SKwa5wwdTgrkQiAAAN",
        "groupId": "goblet"
    },
    {
        "id": "e640c145-aba4-4a97-9797-8074859a397b",
        "message": "Exam - Spec Started",
        "error": false,
        "data": {
            "id": "spec-2",
            "stats": {
                "runEnd": 0,
                "failedSpecs": 0,
                "passedSpecs": 2,
                "passedSuites": 0,
                "failedSuites": 0,
                "runStart": 1695275355735
            },
            "action": "start",
            "testPath": "/suite-0-0/spec-2",
            "fullName": "Scenario > Steps > Then the url should be '$world.secrets.GOBLET_QA_DOCS_URL'",
            "type": "test",
            "failed": false,
            "passed": false,
            "description": "Step - running",
            "timestamp": 1695275357560,
            "metaData": {
                "disabled": false,
                "uuid": "feature-82173692.scenario.0.then.2",
                "step": "the url should be '$world.secrets.GOBLET_QA_DOCS_URL'",
                "index": 7,
                "type": "then"
            },
            "location": "/goblet/repos/lancetipton/goblet/bdd/features/Secrets/Secrets-Url.feature",
            "eventParent": "step"
        },
        "group": "N4SKwa5wwdTgrkQiAAAN",
        "name": "PLAY-SPEC-START",
        "isRunning": false,
        "timestamp": 1695275357563,
        "fullTestRun": true,
        "procId": 20369,
        "runId": "end-2-end.1695275353386",
        "runTimestamp": 1695275353386,
        "location": "/goblet/repos/lancetipton/goblet/bdd/features/Secrets/Secrets-Url.feature",
        "socketId": "N4SKwa5wwdTgrkQiAAAN",
        "groupId": "goblet"
    },
    {
        "id": "c8ca4537-f002-43ce-bb26-caaab5d71712",
        "message": "Exam - Spec Done",
        "error": false,
        "data": {
            "id": "spec-2",
            "stats": {
                "runEnd": 0,
                "failedSpecs": 0,
                "passedSpecs": 3,
                "passedSuites": 0,
                "failedSuites": 0,
                "runStart": 1695275355735
            },
            "action": "end",
            "testPath": "/suite-0-0/spec-2",
            "fullName": "Scenario > Steps > Then the url should be '$world.secrets.GOBLET_QA_DOCS_URL'",
            "type": "test",
            "failed": false,
            "passed": true,
            "description": "Step - passed",
            "timestamp": 1695275357579,
            "metaData": {
                "disabled": false,
                "uuid": "feature-82173692.scenario.0.then.2",
                "step": "the url should be '$world.secrets.GOBLET_QA_DOCS_URL'",
                "index": 7,
                "type": "then"
            },
            "status": "passed",
            "location": "/goblet/repos/lancetipton/goblet/bdd/features/Secrets/Secrets-Url.feature",
            "eventParent": "step"
        },
        "group": "N4SKwa5wwdTgrkQiAAAN",
        "name": "PLAY-SPEC-DONE",
        "isRunning": false,
        "timestamp": 1695275357580,
        "fullTestRun": true,
        "procId": 20369,
        "runId": "end-2-end.1695275353386",
        "runTimestamp": 1695275353386,
        "location": "/goblet/repos/lancetipton/goblet/bdd/features/Secrets/Secrets-Url.feature",
        "socketId": "N4SKwa5wwdTgrkQiAAAN",
        "groupId": "goblet"
    },
    {
        "id": "9fc72de5-5a65-4642-be9b-c0ae4672fc6a",
        "message": "Exam - Spec Started",
        "error": false,
        "data": {
            "id": "spec-3",
            "stats": {
                "runEnd": 0,
                "failedSpecs": 0,
                "passedSpecs": 3,
                "passedSuites": 0,
                "failedSuites": 0,
                "runStart": 1695275355735
            },
            "action": "start",
            "testPath": "/suite-0-0/spec-3",
            "fullName": "Scenario > Steps > Given I click text \"git cloud provider\"",
            "type": "test",
            "failed": false,
            "passed": false,
            "description": "Step - running",
            "timestamp": 1695275357579,
            "metaData": {
                "disabled": false,
                "uuid": "feature-82173692.scenario.0.given.3",
                "step": "I click text \"git cloud provider\"",
                "index": 8,
                "type": "given"
            },
            "location": "/goblet/repos/lancetipton/goblet/bdd/features/Secrets/Secrets-Url.feature",
            "eventParent": "step"
        },
        "group": "N4SKwa5wwdTgrkQiAAAN",
        "name": "PLAY-SPEC-START",
        "isRunning": false,
        "timestamp": 1695275357581,
        "fullTestRun": true,
        "procId": 20369,
        "runId": "end-2-end.1695275353386",
        "runTimestamp": 1695275353386,
        "location": "/goblet/repos/lancetipton/goblet/bdd/features/Secrets/Secrets-Url.feature",
        "socketId": "N4SKwa5wwdTgrkQiAAAN",
        "groupId": "goblet"
    },
    {
        "id": "fc522ac2-69c5-457f-b290-3296e37ee7ef",
        "message": "Exam - Spec Done",
        "error": false,
        "data": {
            "id": "spec-3",
            "stats": {
                "runEnd": 0,
                "failedSpecs": 0,
                "passedSpecs": 4,
                "passedSuites": 0,
                "failedSuites": 0,
                "runStart": 1695275355735
            },
            "action": "end",
            "testPath": "/suite-0-0/spec-3",
            "fullName": "Scenario > Steps > Given I click text \"git cloud provider\"",
            "type": "test",
            "failed": false,
            "passed": true,
            "description": "Step - passed",
            "timestamp": 1695275357781,
            "metaData": {
                "disabled": false,
                "uuid": "feature-82173692.scenario.0.given.3",
                "step": "I click text \"git cloud provider\"",
                "index": 8,
                "type": "given"
            },
            "status": "passed",
            "location": "/goblet/repos/lancetipton/goblet/bdd/features/Secrets/Secrets-Url.feature",
            "eventParent": "step"
        },
        "group": "N4SKwa5wwdTgrkQiAAAN",
        "name": "PLAY-SPEC-DONE",
        "isRunning": false,
        "timestamp": 1695275357782,
        "fullTestRun": true,
        "procId": 20369,
        "runId": "end-2-end.1695275353386",
        "runTimestamp": 1695275353386,
        "location": "/goblet/repos/lancetipton/goblet/bdd/features/Secrets/Secrets-Url.feature",
        "socketId": "N4SKwa5wwdTgrkQiAAAN",
        "groupId": "goblet"
    },
    {
        "id": "d8ce6088-aef3-4a0d-a2a2-cb73f7469fea",
        "message": "Exam - Spec Started",
        "error": false,
        "data": {
            "id": "spec-4",
            "stats": {
                "runEnd": 0,
                "failedSpecs": 0,
                "passedSpecs": 4,
                "passedSuites": 0,
                "failedSuites": 0,
                "runStart": 1695275355735
            },
            "action": "start",
            "testPath": "/suite-0-0/spec-4",
            "fullName": "Scenario > Steps > When I wait for the page to load",
            "type": "test",
            "failed": false,
            "passed": false,
            "description": "Step - running",
            "timestamp": 1695275357781,
            "metaData": {
                "disabled": false,
                "uuid": "feature-82173692.scenario.0.when.4",
                "step": "I wait for the page to load",
                "index": 9,
                "type": "when"
            },
            "location": "/goblet/repos/lancetipton/goblet/bdd/features/Secrets/Secrets-Url.feature",
            "eventParent": "step"
        },
        "group": "N4SKwa5wwdTgrkQiAAAN",
        "name": "PLAY-SPEC-START",
        "isRunning": false,
        "timestamp": 1695275357783,
        "fullTestRun": true,
        "procId": 20369,
        "runId": "end-2-end.1695275353386",
        "runTimestamp": 1695275353386,
        "location": "/goblet/repos/lancetipton/goblet/bdd/features/Secrets/Secrets-Url.feature",
        "socketId": "N4SKwa5wwdTgrkQiAAAN",
        "groupId": "goblet"
    },
    {
        "id": "da5c8970-caa6-463c-bedf-502302746285",
        "message": "Exam - Spec Done",
        "error": false,
        "data": {
            "id": "spec-4",
            "stats": {
                "runEnd": 0,
                "failedSpecs": 0,
                "passedSpecs": 5,
                "passedSuites": 0,
                "failedSuites": 0,
                "runStart": 1695275355735
            },
            "action": "end",
            "testPath": "/suite-0-0/spec-4",
            "fullName": "Scenario > Steps > When I wait for the page to load",
            "type": "test",
            "failed": false,
            "passed": true,
            "description": "Step - passed",
            "timestamp": 1695275357793,
            "metaData": {
                "disabled": false,
                "uuid": "feature-82173692.scenario.0.when.4",
                "step": "I wait for the page to load",
                "index": 9,
                "type": "when"
            },
            "status": "passed",
            "location": "/goblet/repos/lancetipton/goblet/bdd/features/Secrets/Secrets-Url.feature",
            "eventParent": "step"
        },
        "group": "N4SKwa5wwdTgrkQiAAAN",
        "name": "PLAY-SPEC-DONE",
        "isRunning": false,
        "timestamp": 1695275357794,
        "fullTestRun": true,
        "procId": 20369,
        "runId": "end-2-end.1695275353386",
        "runTimestamp": 1695275353386,
        "location": "/goblet/repos/lancetipton/goblet/bdd/features/Secrets/Secrets-Url.feature",
        "socketId": "N4SKwa5wwdTgrkQiAAAN",
        "groupId": "goblet"
    },
    {
        "id": "432001b0-867a-4e78-a662-5f5ec26c5a6d",
        "message": "Exam - Spec Started",
        "error": false,
        "data": {
            "id": "spec-5",
            "stats": {
                "runEnd": 0,
                "failedSpecs": 0,
                "passedSpecs": 5,
                "passedSuites": 0,
                "failedSuites": 0,
                "runStart": 1695275355735
            },
            "action": "start",
            "testPath": "/suite-0-0/spec-5",
            "fullName": "Scenario > Steps > Then the url should be \"https://docs.gobletqa.app/overview/git-providers\"",
            "type": "test",
            "failed": false,
            "passed": false,
            "description": "Step - running",
            "timestamp": 1695275357793,
            "metaData": {
                "disabled": false,
                "uuid": "feature-82173692.scenario.0.then.5",
                "step": "the url should be \"https://docs.gobletqa.app/overview/git-providers\"",
                "index": 10,
                "type": "then"
            },
            "location": "/goblet/repos/lancetipton/goblet/bdd/features/Secrets/Secrets-Url.feature",
            "eventParent": "step"
        },
        "group": "N4SKwa5wwdTgrkQiAAAN",
        "name": "PLAY-SPEC-START",
        "isRunning": false,
        "timestamp": 1695275357795,
        "fullTestRun": true,
        "procId": 20369,
        "runId": "end-2-end.1695275353386",
        "runTimestamp": 1695275353386,
        "location": "/goblet/repos/lancetipton/goblet/bdd/features/Secrets/Secrets-Url.feature",
        "socketId": "N4SKwa5wwdTgrkQiAAAN",
        "groupId": "goblet"
    },
    {
        "id": "d9ba4918-9101-4713-a3ba-d73c2ea9b4d2",
        "message": "Exam - Spec Done",
        "error": false,
        "data": {
            "id": "spec-5",
            "stats": {
                "runEnd": 0,
                "failedSpecs": 0,
                "passedSpecs": 6,
                "passedSuites": 0,
                "failedSuites": 0,
                "runStart": 1695275355735
            },
            "action": "end",
            "testPath": "/suite-0-0/spec-5",
            "fullName": "Scenario > Steps > Then the url should be \"https://docs.gobletqa.app/overview/git-providers\"",
            "type": "test",
            "failed": false,
            "passed": true,
            "description": "Step - passed",
            "timestamp": 1695275357804,
            "metaData": {
                "disabled": false,
                "uuid": "feature-82173692.scenario.0.then.5",
                "step": "the url should be \"https://docs.gobletqa.app/overview/git-providers\"",
                "index": 10,
                "type": "then"
            },
            "status": "passed",
            "location": "/goblet/repos/lancetipton/goblet/bdd/features/Secrets/Secrets-Url.feature",
            "eventParent": "step"
        },
        "group": "N4SKwa5wwdTgrkQiAAAN",
        "name": "PLAY-SPEC-DONE",
        "isRunning": false,
        "timestamp": 1695275357805,
        "fullTestRun": true,
        "procId": 20369,
        "runId": "end-2-end.1695275353386",
        "runTimestamp": 1695275353386,
        "location": "/goblet/repos/lancetipton/goblet/bdd/features/Secrets/Secrets-Url.feature",
        "socketId": "N4SKwa5wwdTgrkQiAAAN",
        "groupId": "goblet"
    },
  ]
}